htd_lync6:
  host: 192.168.2.63  # Replace with the actual IP address of your HTD Lync6 controller
  zones:
    - Master           # Zone 1
    - Ensuite          # Zone 2
    - Living           # Zone 3
    - Basement         # Zone 4
    - Patio            # Zone 5
    - Garage           # Zone 6
  sources:
    - NA 1             # Source 1
    - NA 2             # Source 2
    - Living Room TV   # Source 3
    - Basement TV      # Source 4
    - NA 5             # Source 5
    - NA 6             # Source 6
    - NA 7             # Source 7
    - MusicCast        # Source 8
    - NA 9             # Source 9
    - NA 10            # Source 10
    - NA 11            # Source 11
    - NA 12            # Source 12

